akka {
    loglevel = INFO
    stdout-loglevel = INFO

    actor {
        deployment {

            "/topicModelingActor" {
                dispatcher = topic-modeling-dispatcher
            }
        }
    }
}

topic-modeling-dispatcher {
    type = Dispatcher
    executor = "thread-pool-executor"
    thread-pool-executor {
        fixed-pool-size = 4
    }
    throughput = 5
}
